# This is a basic workflow to help you get started with Actions

name: Auto-Approve PRs

# Controls when the workflow will run
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "You have been auto-approved"
